volumes:
  postgresql_etc:
  postgresql_log:
  postgresql_data:


services:
  database:
    container_name: diary-postgresql
    image: postgres:17.2-alpine3.21
    ports:
      - "5432:5432"
    volumes:
      - postgresql_etc:/etc/postgresql/
      - postgresql_log:/var/log/postgresql/
      - postgresql_data:/var/lib/postgresql/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    container_name: diary-backend
    build:
      context: diary-backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://diary-postgresql:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    container_name: diary-frontend
    build:
      context: diary-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
      - database
    ports:
      - "8081:80"
